language: go
go:
  - 1.2
  
install:
  - go get -v ./...
  - go get github.com/pivotal/gumshoe/repos/ginkgo
  - go install github.com/pivotal/gumshoe/repos/ginkgo/ginkgo

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --failOnPending
